### ISSUE TITLE
Automatically clear search bar after every search

### ISSUE THREAD

**Issue by ar-ag** [avinash201199/weather-app#107]
In the present UI the value of searched item is displayed in the search bar even after entering the city name. So to enter another city user has to clear the search bar manually and then search for the city.
If after every search the search bar clears automatically, it will enhance user experience.

![Screenshot (27)](https://user-images.githubusercontent.com/96348217/194729353-4bbd025e-b13a-451d-b47e-6e0bb99c5750.jpg)
The marked 'Ahmedabad' should clear up after getting the weather data for 'Ahmedabad', so that the user can easily enter a new city, without the need to manually clear the search bar.

I know the solution to this issue, please assign me this issue.

**Comment by Zeuhz-Droid** [comment]
I would like to take on this issue
