### ISSUE TITLE
Showing loader while data s fetched

### ISSUE THREAD

**Issue by pavan-choudhary** [avinash201199/weather-app#116]
Showing a full screen loader(raining clouds) while the data is fetched, so the broken page is not seen.

**Comment by Kishore-abhimanyu** [comment]
Can you assign this to me so that i can start working on it?

**Comment by Kishore-abhimanyu** [comment]
Also is there any specific loader you want to be displayed?

**Comment by pavan-choudhary** [comment]
Already made a PR for the same
