### ISSUE TITLE
Fix: UI suggestions

### ISSUE THREAD

**Issue by mateahoward** [avinash201199/weather-app#16]
Hi! here are a few suggestions I'd like to add to your project:

SEO:
- a missing meta description 
- `<h1>` and `<h2>` elements are not in a correct order

Accessibility:
- the search button with a magnifying glass icon does not have an accessible name
- the input field does not have an indicator for when an element is in focus
- the input field does not have an autocomplete attribute
- the input field does not have a label

General:
- document does not have a` <main>` element 

If you'd like me to work on this please assign this issue to me 😸

**Comment by Ultron03** [comment]
Hello I am new to  Open source contribution and had idea which related to the Forecast  predictions Showing  so can you help me like what to I do next ...(Should I just fork it add the idea and make pull request?).

**Comment by mateahoward** [comment]
Hi @avinash201199, I've submitted a PR here https://github.com/avinash201199/weather-app/pull/20. If you're happy with the changes then we can close this issue 😄
