### ISSUE TITLE
Fixing missing closing span tag

### ISSUE THREAD

**Issue by milostivyy** [avinash201199/weather-app#224]
Hi, I spotted there is a missing closing span tag in line no-25 in the index.html file. Can you assign me this issue so that I can fix it?

**Comment by avinash201199** [comment]
sure , but if you can add more code or anything to contribute because adding 1,2 words might create problem for quality contribution, and hacktoberfest review every pr .

**Comment by milostivyy** [comment]
yes,sure!

**Comment by milostivyy** [comment]
In the temperature toggle in input and label in lines no 29 and 30 I think the 'for' attribute should be compared with the 'id' attribute ie -"unit" but it is matched with the class attribute. Could you check this I would like to fix this bug.

**Comment by avinash201199** [comment]
> In the temperature toggle in input and label in lines no 29 and 30 I think the 'for' attribute should be compared with the 'id' attribute ie -"unit" but it is matched with the class attribute. Could you check this I would like to fix this bug.

you can work on it !
