### ISSUE TITLE
Make the background a bit blurry

### ISSUE THREAD

**Issue by Ritesh-Dabral** [avinash201199/weather-app#225]
Make the background a bit blurry so that the focus of the user goes directly to the interface and details while also maintaining the UX and scenic view. 
Also, load background images based on mobile and desktop view so as to increase the performance 

<img width="923" alt="Screenshot 2023-10-01 at 6 15 00 PM" src="https://github.com/avinash201199/weather-app/assets/36252036/234d3fd3-e415-4f66-b6da-50363c7f5bb2">

**Comment by Ritesh-Dabral** [comment]
@avinash201199 Kindly assign this issue to me

**Comment by anish-patro** [comment]
Is this issue currently available? If yes please assign it to me.

**Comment by avinash201199** [comment]
> Is this issue currently available? If yes please assign it to me.

completed
