### ISSUE TITLE
Air Quality section showing undefined in case of some city

### ISSUE THREAD

**Issue by milan604** [avinash201199/weather-app#234]
When selecting certain cities, the Air Quality section displays 'undefined,' as seen in the screenshot below.
<img width="763" alt="Screenshot 2023-10-02 at 8 01 45 AM" src="https://github.com/avinash201199/weather-app/assets/30483005/ab5896e7-5d2c-45ed-a92e-6f1002c654f9">

**Comment by milan604** [comment]
Fix: https://github.com/avinash201199/weather-app/pull/237

**Comment by Kokonodray2001** [comment]
@milan604 can you assign me this issue i can fix it #237

**Comment by Kokonodray2001** [comment]
> @milan604 can you assign me this issue i can fix it #237

**Comment by milan604** [comment]
Already fixed here https://github.com/avinash201199/weather-app/pull/237 @Kokonodray2001
