### ISSUE TITLE
The WhatsApp button goes behind and is inaccessible in mobile viewport

### ISSUE THREAD

**Issue by Avilash-Saha** [avinash201199/weather-app#258]
The WhatsApp button goes behind and is inaccessible in mobile viewport. Please allow me to fix this issue under Hacktoberfest23
![WhatsApp Image 2023-10-04 at 16 04 21_0588b6fd](https://github.com/avinash201199/weather-app/assets/85384757/f305db9c-fa91-4d8a-9acc-179d9731f64c)

**Comment by Kathuria** [comment]
@avinash201199 : Can I work on this issue?

-- @Avilash-Saha

**Comment by Kathuria** [comment]
This issue seems fixed, can be closed. @avinash201199
