### ISSUE TITLE
Loading should be in centre and also other UI need to be fix as device change 

### ISSUE THREAD

**Issue by AAKASHBANSAL96** [avinash201199/weather-app#264]
Loading should be in centre also responsive

![image](https://github.com/avinash201199/weather-app/assets/146818230/f88abc4f-76d5-4d8e-8bf1-f383eaa0a123)

Assign this to me, I can make it responsive and fix UI issues.

**Comment by Kathuria** [comment]
@avinash201199 / @AAKASHBANSAL96 : Can I work on this issue?

**Comment by Kathuria** [comment]
This looks fixed, @avinash201199 this can be closed.

**Comment by avinash201199** [comment]
> This looks fixed, @avinash201199 this can be closed.

thank you for letting me know :)
