### ISSUE TITLE
Add API Keys to Environment file

### ISSUE THREAD

**Issue by leabuende** [avinash201199/weather-app#273]
The API keys are visible in the repo. Please assign this issue to me so I can add an environment file and keep those API keys safe.
If you want contributors to still have access to the API keys, I can add a default .env file, but it is still a better practice to keep them away from the app repo

**Comment by veerendra19codes** [comment]
Hey @avinash201199 is this issue still open ? I can solve this issue. Please assign me this issue it will hardly take any time .Thank you
