### ISSUE TITLE
Integrating a gulp task runner with css minify & watch tasks 

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [avinash201199/weather-app#279]
@avinash201199 

Gulp task runner will generates, auto saves the css & produces a minification of all css files.

Will integrate gulp task runner 

Can you assign this to me ?

**Comment by avinash201199** [comment]
what will be the use of that ? how it will help in the project ?

**Comment by Prakash-Ravichandran** [comment]
**- Automatically reload the page in the browser after changes.
- Watch for changes in your files and act on it.
- How to set up an automated workflow.
- How to compile SASS into CSS.**

Of course there are lots of gulp advantages, i see the above four are concrete advantage.

**Comment by avinash201199** [comment]
okay , work on the issue , while making pr , please also add demo video of the changes
