### ISSUE TITLE
Stylize the cards showing temperature for the week

### ISSUE THREAD

**Issue by Divyanshi014** [avinash201199/weather-app#313]
Adding a glassphormism effect on these cards, to make them more attractive.

**Comment by Honeshwar** [comment]
what about this: **Style**
![Stylize the cards showing temperature for the week · Issue #313 · avinash201199_weather-app - Google Chrome 26-10-2023 15_03_38](https://github.com/avinash201199/weather-app/assets/73346917/fe341775-e6f3-4865-90c5-1b6f1cf8d3b2)

**Comment by Honeshwar** [comment]
okay,
