### ISSUE TITLE
Feature: Adding favicon to the weather-app website

### ISSUE THREAD

**Issue by AishwaryaParab** [avinash201199/weather-app#37]
I wish to add the following png image as the favicon:

![weather-icon](https://user-images.githubusercontent.com/65883954/193549290-b69bbb3b-0b87-460a-9c60-5fcd2fa52104.png)

**Comment by AishwaryaParab** [comment]
@avinash201199 could you please assign this issue to me?

**Comment by sukalyanbisui** [comment]
could you please assign this issue to me

**Comment by itsaman123** [comment]
Please assign this issue to me
