### ISSUE TITLE
ANIMATED-BACKGROUND

### ISSUE THREAD

**Issue by sourabh1428** [avinash201199/weather-app#50]
Animated Backgroud would look more cool. 
Assign it to me for hacktoberfest

**Comment by avinash201199** [comment]
autoupdated background image is also good but you can try

**Comment by sourabh1428** [comment]
assign me under hactoberfest

**Comment by c99SRS** [comment]
Hi @avinash201199 if sourabh hasn't done yet, then I can work on this
